# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Extrato(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, transacoes: List[Transacao]=None):  # noqa: E501
        """Extrato - a model defined in Swagger

        :param transacoes: The transacoes of this Extrato.  # noqa: E501
        :type transacoes: List[Transacao]
        """
        self.swagger_types = {
            'transacoes': List[Transacao]
        }

        self.attribute_map = {
            'transacoes': 'transacoes'
        }

        self._transacoes = transacoes

    @classmethod
    def from_dict(cls, dikt) -> 'Extrato':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Extrato of this Extrato.  # noqa: E501
        :rtype: Extrato
        """
        return util.deserialize_model(dikt, cls)

    @property
    def transacoes(self) -> List[Transacao]:
        """Gets the transacoes of this Extrato.


        :return: The transacoes of this Extrato.
        :rtype: List[Transacao]
        """
        return self._transacoes

    @transacoes.setter
    def transacoes(self, transacoes: List[Transacao]):
        """Sets the transacoes of this Extrato.


        :param transacoes: The transacoes of this Extrato.
        :type transacoes: List[Transacao]
        """

        self._transacoes = transacoes
